### ISSUE TITLE
Vote up/down wrong response

### ISSUE THREAD

**Issue by darylmarqueta** [neilmarion/paano#107]
On "Answer page", sometime vote up/down is not working well. For example, nagpress ako ng up so +1 na yung votes then nagpress ako uli ng up, nagiging -1 na yung votes.

**Comment by neilmarion** [comment]
Para ma-unvote ang isang post, kelangan mo rin talagang i-repress yung chevron na 'may-kulay' na. Yan ba nangyayari sa'yo? Paki-verify.

**Comment by darylmarqueta** [comment]
ok

**Comment by neilmarion** [comment]
Kulang lang talaga sa notifications. Hehe. Pag nagkaroon talaga ako ng 1 day, WHO-YOU sa akin ang mga issues na 'yan.
