### ISSUE TITLE
Sign up or log in message to vote/comment/answer

### ISSUE THREAD

**Issue by darylmarqueta** [neilmarion/paano#108]
When user is currently not logged in, maybe a message box should be displayed. Something like this,

http://stackoverflow.com/questions/16650680/given-f-is-there-an-automatic-way-to-calculate-fprime-for-newtons-method

**Comment by neilmarion** [comment]
Please attach screenshot. Luma-login ako sa stackoverflow automatically eh. Though may mga issues talaga na 'mejo simple' na di ko naaaaddress.

**Comment by darylmarqueta** [comment]
non-sense magscreenshot. papakita ko lang din yung paano page. basta pag di naka-login, walang response. pwede ka magclick, etc pero walang response. tama naman yun kaso nga lang, better kung may message box na nagsasabi na "mag-login ka muna bago ka makapagcomment/vote/answer"

**Comment by neilmarion** [comment]
Hahaha! Tama ka jan. Kaya nga may issue na para diyan. #90 Di ko palang nareresolve.
