### ISSUE TITLE
Users must be able to share their question in Facebook

### ISSUE THREAD

**Issue by neilmarion** [neilmarion/paano#55]
Nuff said.

**Comment by ketchisauplb** [comment]
agree. though the tabs with this button is still not working. only the expand button is working. 
![tabs not working](https://f.cloud.github.com/assets/4350651/465723/dba602c4-b63f-11e2-8645-62a8b9bee2b4.jpg)

vote up. vote down, and share buttons not working

**Comment by neilmarion** [comment]
Haha. This issue is not yet closed meaning to say I am yet to resolve this issue i.e. gonna push the code for this. As long as I have resolved an issue, you can manual test that. Reopen the issue if it's not yet resolved yet (found bugs or whatnot) after I closed it.

**Comment by neilmarion** [comment]
Resolved. But there's a bug - #80
