### ISSUE TITLE
Improve the sign-in page

### ISSUE THREAD

**Issue by neilmarion** [neilmarion/paano#64]
Nuff said.

**Comment by ketchisauplb** [comment]
Are we limited to sign in using fb accounts? Users without fb account would really need to create one? thanks

**Comment by neilmarion** [comment]
We shouldn't worry about users without FB user accounts. Almost every person now has an FB account. We need to be simple and straightforward. But in the future we should allow login through Twitter, Google, etc.

Read "REWORK" by DHH. I emailed that to you. That's a nice read. Read ASAP. :P

**Comment by ketchisauplb** [comment]
ok thanks reading
