### ISSUE TITLE
Error in signing up using facebook link

### ISSUE THREAD

**Issue by ketchisauplb** [neilmarion/paano#67]
Error in signing up using facebook link

http://www.uplb.paano.org/users/auth/facebook/callback?error_code=2&error_message=Sorry%2C%20this%20feature%20isn't%20available%20right%20now%3A%20An%20error%20occurred%20while%20processing%20this%20request.%20Please%20try%20again%20later.#_=

**Comment by ketchisauplb** [comment]
still same concern using the .info staging site
http://www.staging.uplb.paano.info/users/auth/facebook/callback?error_code=901&error_message=This+app+is+in+sandbox+mode.++Edit+the+app+configuration+at+http%3A%2F%2Fdevelopers.facebook.com%2Fapps+to+make+the+app+publicly+visible.#_=_

**Comment by neilmarion** [comment]
Made you a "tester" role at the Paano? UPLB fb app.

**Comment by ketchisauplb** [comment]
done thank you
