### ISSUE TITLE
connection interupted/ possible server concern

### ISSUE THREAD

**Issue by ketchisauplb** [neilmarion/paano#69]
date: 05/06/13
time : 7:36 pm phil time

![interupted](https://f.cloud.github.com/assets/4350651/465753/56ccd6c0-b641-11e2-973a-3573a2252a18.jpg)

tried logging in couple of time, not working. server related concerns?

**Comment by neilmarion** [comment]
Linode had a scheduled maintenance. https://www.dropbox.com/s/mqdxs6gzmj6t89c/Selection_082.png Server matter.

**Comment by ketchisauplb** [comment]
ok thanks
