### ISSUE TITLE
Tags are unsearchable

### ISSUE THREAD

**Issue by ketchisauplb** [neilmarion/paano#71]
Search option does not apply to tags? see pic
![tag](https://f.cloud.github.com/assets/4350651/475651/4dc95b3e-b79a-11e2-9831-f9db8bc02704.jpg)

my tag "type"
seems to be unsearchable

**Comment by neilmarion** [comment]
Hahaha! This does not apply yet Mr. Alvin. But this will be a feature in the future. This is not yet included in the first release.

**Comment by neilmarion** [comment]
Though you can create another issue with the "enhancement" label then assign it to me.

**Comment by neilmarion** [comment]
I think tags are really unsearchable. The purpose of tags are for filtering posts, not for full-text searching.

**Comment by neilmarion** [comment]
#30
