### ISSUE TITLE
Recent button shows oldest questions first

### ISSUE THREAD

**Issue by ketchisauplb** [neilmarion/paano#72]
Should the recent button show oldest question first? rather than showing most recent questions?

**Comment by neilmarion** [comment]
The recent button should show the latest questions/answers made.

**Comment by ketchisauplb** [comment]
unfortunately our most recent questions are on the last page :( its a bug sir.

![recent bug](https://f.cloud.github.com/assets/4350651/487251/50c7e9b0-b950-11e2-8988-e988da49a310.png)

**Comment by neilmarion** [comment]
Haha. Sorry to not realize this. Fix is coming up.

**Comment by neilmarion** [comment]
Bug fix pushed to staging. Please check.
