### ISSUE TITLE
Something went wrong! after hitting the recent button

### ISSUE THREAD

**Issue by ketchisauplb** [neilmarion/paano#74]
this error only shows when you browse the page directory after hitting recent button,

![bug 2](https://f.cloud.github.com/assets/4350651/488137/3a0f120a-b975-11e2-829b-d888a9b697ac.jpg)

on normal home page/ or after hitting the paano logo there is no such error

![bug3](https://f.cloud.github.com/assets/4350651/488140/96c21ca4-b975-11e2-9a34-8601be34a782.png)

**Comment by neilmarion** [comment]
Hey. Is the problem still occuring?

**Comment by ketchisauplb** [comment]
its ok now

**Comment by neilmarion** [comment]
Nice. On an unrelated matter, are you receiving emails whenever I do something on this github repository?
