### ISSUE TITLE
Vote up/down not responding sometimes

### ISSUE THREAD

**Issue by darylmarqueta** [neilmarion/paano#85]
yung vote up/down minsan hindi nagreresponse. minsan ok yung vote pero kailangan i-reload yung page pra mag-update

**Comment by neilmarion** [comment]
Paki-confirm nga kung nangyayari ang ito kapag may votes existing na. Maayos kasi pag first time magvote dun sa post.

**Comment by neilmarion** [comment]
Only happens when javascript files are not loaded properly because of The Facebook sharing bug!!! #80
